//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeComparer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcode
    {
        public int BarcodeId { get; set; }
        public string SequenceNumber { get; set; }
        public string CardNumber { get; set; }
        public string Barcodes { get; set; }
        public string LeanBarcode { get; set; }
        public string BarcodeItem { get; set; }
        public string LeanBarcodeItem { get; set; }
        public string Filename { get; set; }
        public string Matched { get; set; }
        public string Finalized { get; set; }
        public string PrintBatch { get; set; }
        public string Batch { get; set; }
        public string FinalBarcode { get; set; }
        public System.DateTime DateTime { get; set; }
        public string User { get; set; }
    }
}
