//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeComparer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatsonsView
    {
        public string SequenceNumber { get; set; }
        public string Barcodes { get; set; }
        public string Barcoded { get; set; }
        public string Finalized { get; set; }
        public string Released_Batch { get; set; }
        public string Batch { get; set; }
    }
}
